app/blueprints/authentication/models.py
from app import db, login
from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String)
    last_name = db.Column(db.String)
    email = db.Column(db.String, unique=True)
    password = db.Column(db.String)
    created_on = db.Column(db.DateTime, default=datetime.utcnow)

    def hash_password(self, original_password):
        self.password = generate_password_hash(original_password)

    def check_password(self, original_password):
        return check_password_hash(self.password, original_password)

    def __repr__(self):
        return f"<User: {self.email}>"

@login.user_loader
def login_user(id):
    return User.query.get(int(id))

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_moment import Moment

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
moment = Moment()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    moment.init_app(app)
    
    login.init_app(app)
    login.login_view = 'authentication.login'
    login.login_message_category = 'warning'

    from app.blueprints.authentication import bp as authentication
    app.register_blueprint(authentication)

    with app.app_context():
        from app.blueprints.main import bp as main
        app.register_blueprint(main)

    from .import routes, models

    return app

app/blueprints/authentication/__init__.py
from flask import Blueprint

bp = Blueprint('authentication', __name__, url_prefix='/authentication')

from .import routes, models

app/blueprints/authentication/routes.py
from app import db
from flask import request, render_template, flash, redirect, url_for
from .import bp as authentication
from app.blueprints.authentication.models import User
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.urls import url_parse

@authentication.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        r = request.form
        if r.get('confirm_password') == r.get('password'):
            data = {
                'first_name': r.get('first_name'),
                'last_name': r.get('last_name'),
                'email': r.get('email'),
                'password': r.get('password'),
            }
            u = User(first_name=data['first_name'], last_name=data['last_name'], email=data['email'], password=data['password'])
            u.hash_password(u.password)
            db.session.add(u)
            db.session.commit()
            flash("You have registered successfully", 'primary')
            return redirect(url_for('authentication.login'))
    return render_template('register.html')

@authentication.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        r = request.form
        user = User.query.filter_by(email=r.get('email')).first()
        if user is None or not user.check_password(r.get('password')):
            flash("You have used either an incorrect email or password", 'danger')
            return redirect(url_for('authentication.login'))
        login_user(user, remember=r.get('remember_me'))
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('index')
        flash("You have logged in successfully", 'success')
        return redirect(next_page)
    return render_template('login.html')

@authentication.route('/logout')
@login_required
def logout():
    logout_user()
    flash("You have successfully logged out", 'info')
    return redirect(url_for('authentication.login'))

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, url_prefix='/')

from .import routes

app/blueprints/main/routes.py
from flask import current_app as app, render_template

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/whatwedo')
def whatwedo():
    return render_template('whatwedo.html')

@app.route('/wherewework')
def wherewework():
    return render_template('wherewework.html')

@app.route('/whoweare')
def whoweare():
    return render_template('whoweare.html')

@app.route('/attorneys')
def attorneys():
    return render_template('attorneys.html')

@app.route('/contactus')
def contactus():
    return render_template('contactus.html')

@app.route('/news')
def news():
    return render_template('news.html')

app/templates/contactus.html
{% extends 'layout.html' %}
{% set active_page='main.contactus' -%}

{% block title %}
{{ super() }} | Contact Us
{% endblock %}

{% block body %}
<main>
    <div class="row">
        <div class="col-md-3" style="padding-left: 0px;">
            <div id="www-sidebar">
                <div id="www-sidebar-content">
                    <h5 class="sidebar-title">Contact Us</h5>
                    <ul class="list-unstyled">
                        <div class="category">
                            <a href="#">Directions/Parking</a>
                        </div>
                        <div class="category">
                            <a href="#">Career Opportunities</a>
                        </div>
                        <div class="sidebar-footer">
                            <a href="#">
                                <img style="width: 100%" class="img-fluid" src="./static/images/content-navlink-news.jpg"
                                    alt="">
                            </a>
                        </div>
                        <div class="sidebar-content-bottom">
                            <div><strong>News &amp; Events</strong></div>
                            <div>Join our magnificent firm and do more stuff with us.</div>
                        </div>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <img src="./static/images/content-05-contact.jpg" alt="" class="img-fluid" style="width: 100%;">
                </div>
            </div>
            <div class="row contact-container">
                <div class="col-md-12">
                    <p>The office hours are 8am - 5pm Monday through Friday</p>
                    <p>
                    <div>689 East South Street</div>
                    <div>Suite 4210</div>
                    <div>Houston, Texas 09324</div>
                    </p>
                    <p>PH: 555.555.5555</p>
                    <p>FAX: 555.555.5555</p>
                    <p>Contact Rosemary Sage at <a href="mailto: rosemary@lawfirm.com">rosemary@lawfirm.com</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-3" style="padding-left: 0px;">
            <div id="contact-sidebar">
                <div id="contact-sidebar-content">
                    <ul class="list-unstyled">
                        <img style="width: 100%" class="img-fluid" src="./static/images/content-link-where.jpg" alt="">
                        <div class="contact-text sidebar-content-bottom">
                            <div class="red-text"><strong>Where We Work</strong></div>
                            <div class="red-text">Find out more about our work coverage area</div>
                        </div>
                        <div class="sidebar-footer">
                            <a href="#">
                                <img style="width: 100%" class="img-fluid" src="./static/images/content-link-reputation.jpg"
                                    alt="">
                            </a>
                        </div>
                        <div class="sidebar-content-bottom">
                            <div style="color: black;"><strong>News &amp; Events</strong></div>
                            <div style="color: black;">Join our magnificent firm and do more stuff with us.</div>
                        </div>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

app/templates/index.html
{% extends 'layout.html' %}
{% set active_page='main.index' -%}

{% block title %}
{{ super() }} | Home
{% endblock %}

{% block body %}
<main>
    <div class="row">
        <div class="col-md-9">
            <img class="slideshow" width="100%" src="./static/images/nza_slideshow.jpg" alt="">
        </div>
        <div class="col-md-3" style="padding-left: 0px;">
            <div id="sidebar">
                <div id="sidebar-content">
                    <h5 class="sidebar-title">News Feed</h5>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint non delectus minima consectetur
                        nemo
                        provident molestias repudiandae perferendis nobis, autem consequatur earum corporis, dolor
                        officiis
                        debitis ut nisi voluptatem placeat.</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint non delectus minima consectetur
                        nemo
                        provident molestias repudiandae perferendis nobis, autem consequatur earum corporis, dolor
                        officiis
                        debitis ut nisi voluptatem placeat.</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint non delectus minima consectetur
                        nemo
                        provident molestias repudiandae perferendis nobis, autem consequatur earum corporis, dolor
                        officiis
                        debitis ut nisi voluptatem placeat.</p>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint non delectus minima consectetur
                        nemo
                        provident molestias repudiandae perferendis nobis, autem consequatur earum corporis, dolor
                        officiis
                        debitis ut nisi voluptatem placeat.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row extra-content">
        <div class="col-md-9">
            <div class="small-title">
                <strong>Welcome to our website!</strong>
            </div>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Reiciendis nam dolor consequatur qui assumenda
                reprehenderit odio possimus delectus perspiciatis, sit fuga. Itaque quia distinctio eum quod nulla
                voluptatum
                voluptatem repellat!</p>
        </div>
        <div class="col-md-3" style="padding-left: 0;">
            <div class="small-title">
                <strong>Bigshot, Zoo, & Adds, P.C.</strong>
            </div>
            <div>419 West South Street, Suite 4200</div>
            <div>Houston, Texas 35983</div>
            <div>555-555-5555 (Phone)</div>
            <div>555-555-5555 (Fax)</div>
            <div></div>
        </div>
    </div>
</main>
{% endblock %}

app/templates/layout.html
{% set navigation_bar = [
    ('/', 'main.index', 'Home'),    
    ('/whatwedo', 'main.whatwedo', 'What We Do'),
    ('/news', 'main.news', 'News & Events'),
    ('/wherewework', 'main.wherewework', 'Where We Work'),
    ('/whoweare', 'main.whoweare', 'Who We Are'),
    ('/contactus', 'main.contactus', 'Contact Us'),
] -%}

{% set active_page = active_page|default('main.index') -%}

<!doctype html>
<html lang="en">

<head>
  <title>
    {% block title %}
    Lawfirm
    {% endblock %}
  </title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>

<body>
  <div class="woodenbackground container-fluid" id="wood">
    <div class="row justify-content-center">
      <div class="col-8 paperpiece shadow-lg">
        <header>
          <!------------------------------header image -ken ------------------------->
          <div class="container">
            <div class="row">
              <div class="col-md-5">
                <img src="https://via.placeholder.com/318x76.png" class="img-fluid a" alt="random image" />
              </div>
              <div class="col-md-4">
              </div>
              <div class="col-md-2">
                <div class="login_reg">
                  <div type="button" class="login_reg btn btn-sm btn-block btn-outline-primary create_btn">
                    {% if current_user.is_authenticated %}
                    <a class="login_b" href="{{ url_for('authentication.logout') }}">LOGOUT</a>
                    {% else %}
                    <a class="login_b" href="{{ url_for('authentication.login') }}">LOGIN</a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- navbar for all pages -SD-->
          {% include './partials/navigation.html' %}

        </header>
        <main>
          {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
          {% for c, m in messages %}
          <!-- b4-alert-closable -->
          <div class="alert alert-{{ c }} alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <strong>{{ m }}</strong>
          </div>
          {% endfor %}
          {% endif %}
          {% endwith %}
          <!-- FLASH MESSAGES - END -->

          {% block body %}
          <!-- MAIN CONTENT HERE -->
          {% endblock %}
        </main>

        <footer>
          <div class="row fluid justify-content-center" id="f3">
            <div class="col-md">
              <p class="p1" id="before"><a href="{{ url_for('index') }}" class="f1">HOMEPAGE</a></p>
            </div>
            <div class="col-md">
              <p class="p1"><a href="{{ url_for('whatwedo') }}" class="f1">WHAT WE DO</a></p>
            </div>
            <div class="col-md">
              <p class="p1"><a href="{{ url_for('wherewework') }}" class="f1">WHERE WE WORK</a></p>
            </div>
            <div class="col-md">
              <p class="p1"><a href="{{ url_for('whoweare') }}" class="f1">WHO WE ARE</a></p>
            </div>
            <div class="col-md">
              <p class="p1"><a href="{{ url_for('news') }}" class="f1">NEWS & EVENTS</a></p>
            </div>
            <div class="col-md">
              <p class="p1" id="after"><a href="{{ url_for('contactus') }}" class="f1">CONTACT US</a></p>
            </div>
          </div>
          <div>
            <p class="text-center f2">© 2018 Conor Miliken</p>
          </div>
        </footer>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        {% block scripts %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
          integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
          crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
          integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
          crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
          integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
          crossorigin="anonymous"></script>
        {{ moment.include_jquery() }}
        {{ moment.include_moment() }}
        {% endblock %}
      </div>
    </div>
  </div>
</body>


</html>

app/templates/login.html
{% extends 'layout.html' %}
{% set active_page='authentication.login' -%}

{% block title %}
{{ super() }} | Login
{% endblock %}

{% block body %}
<div class="row justify-content-center">
    <div class="col-md-4">
        <h3 class=>Login Page</h3>
        <hr>
        <form method="POST">
            <div class="form-group">
                <input type="text" class="form-control" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="password" placeholder="Password">
            </div>
            <div class="form-group">
                <!-- b4-form-checkbox -->
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="checkbox" class="form-check-input" name="remember_me">
                        Remember Me
                    </label>
                </div>
            </div>
            <div class="form-group">
                <p>Don't have an account? <a id="register-link" href="./register">Register here.</a></p>
            </div>
            <div class="form-group">
                <input id="form-submit" type="submit" class="btn btn-outline-dark" value='Submit' />
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/news.html
{% extends 'layout.html' %}
{% set active_page='main.news' -%}

{% block title %}
{{ super() }} | News & Events
{% endblock %}

{% block body %}
<!-- Weather Widget Here -->
{% endblock %}

app/templates/partials/navigation.html
<div class="navigation">
    <nav class="navbar nav-pills nav-fill">
        {% for href, id, caption in navigation_bar %}
        <a class="nav-item nav-link" id="{% if id == active_page %}active{% endif %}" 
        href="{{ href|e }}">{{ caption|e }}</a>
        {% endfor %}
    </nav>
</div>

app/templates/register.html
{% extends 'layout.html' %}
{% set active_page='authentication.register' -%}

{% block title %}
{{ super() }} | Register
{% endblock %}

{% block body %}
<div class="row justify-content-center">
    <div class="col-md-4">
        <h3>Register Page</h3>
        <hr>
        <form method="POST" action="{{ url_for('authentication.register') }}">
            <div class="form-group">
                <input type="text" class="form-control" name="first_name" placeholder="First Name">
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="last_name" placeholder="Last Name">
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="password" placeholder="Password">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="confirm_password" placeholder="Confirm Password">
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-outline-dark" value='Submit' />
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/whatwedo.html
{% extends 'layout.html' %}
{% set active_page='main.whatwedo' -%}

{% block title %}
{{ super() }} | What We Do
{% endblock %}

{% block body %}
<main>
    <div class="row">
        <div class="col-md-3" style="padding-left: 0px;">
            <div id="wwd-sidebar">
                <div id="wwd-sidebar-content">
                    <h5 class="sidebar-title">What We Do</h5>
                    <ul class="list-unstyled">
                        <div class="category">
                            Subrogation
                            <li>
                                <a href="#">
                                    Property
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Workers' Comp
                                </a>
                            </li>
                        </div>
                        <div class="category">
                            Litigation
                            <li>
                                <a href="#">
                                    Appeliate
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Commercial
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Defense
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Labor/Employment
                                </a>
                            </li>
                        </div>
                        <div class="category">
                            Business
                            <li>
                                <a href="#">
                                    Brokerage Agreement
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Business Formation
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Business Related Contracts
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Property</li>
                            </a>
                            <li>
                                <a href="#">
                                    Labor/Employment
                                </a>
                            </li>
                        </div>
                        <div class="category">
                            Transportation
                            <li>
                                <a href="#">
                                    Brokerage Agreement
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Business Formation
                                </a>
                            </li>
                        </div>
                        <div class="sidebar-footer">
                            <a href="#">
                                <img style="width: 100%" class="img-fluid" src="./static/images/content-navlink-attorneys.jpg"
                                    alt="">
                            </a>
                        </div>
                        <div class="sidebar-content-bottom">
                            <div><strong>Attorneys</strong></div>
                            <div>Lorem ipsum dolor sit amet consectetur, adipisicing elit.</div>
                        </div>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="row">
                <div class="col-md-12">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia, dolor rem iste id cupiditate
                        ipsam.
                        Laborum ab voluptatibus praesentium error, eius nobis reprehenderit laudantium tempora
                        voluptates
                        dignissimos excepturi quidem odit? Quia, dolor rem iste id cupiditate ipsam.
                        Laborum ab voluptatibus praesentium error, eius nobis reprehenderit laudantium tempora
                        voluptates
                        dignissimos excepturi quidem odit? Quia, dolor rem iste id cupiditate ipsam.
                        Laborum ab voluptatibus praesentium error, eius nobis reprehenderit laudantium tempora
                        voluptates
                        dignissimos excepturi quidem odit?</p>
                </div>
            </div>
            <div class="row link-container">
                <div class="col-md-6">
                    <a href="#">
                        <img src="./static/images/sub-02-subrogation.jpg" alt="Subrogation">
                    </a>
                </div>
                <div class="col-md-6">
                    <a href="#">
                        <img src="./static/images/sub-02-litigation.jpg" alt="Subrogation">
                    </a>
                </div>
                <div class="col-md-6">
                    <a href="#">
                        <img src="./static/images/sub-02-business.jpg" alt="Subrogation">
                    </a>
                </div>
                <div class="col-md-6">
                    <a href="#">
                        <img src="./static/images/sub-02-warehouse.jpg" alt="Subrogation">
                    </a>
                </div>
            </div>
        </div>

    </div>
</main>
{% endblock %}

app/templates/wherewework.html
{% extends 'layout.html' %}
{% set active_page='main.wherewework' -%}

{% block title %}
{{ super() }} | Where We Work
{% endblock %}

{% block body %}
<main>
    <div class="row">
        <div class="col-md-3" style="padding-left: 0px;">
            <div id="www-sidebar">
                <div id="www-sidebar-content">
                    <h5 class="sidebar-title">Where We Work</h5>
                    <ul class="list-unstyled">
                        <div class="category">
                            <a href="#">United States</a>
                        </div>
                        <div class="category">
                            <a href="#">International</a>
                        </div>
                        <div class="sidebar-footer">
                            <a href="#">
                                <img style="width: 100%" class="img-fluid" src="./static/images/content-navlink-career.jpg"
                                    alt="">
                            </a>
                        </div>
                        <div class="sidebar-content-bottom">
                            <div><strong>Career Opportunities</strong></div>
                            <div>Join our magnificent firm.</div>
                        </div>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="row">
                <div class="col-md-12">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia, dolor rem iste id cupiditate
                        ipsam.
                        Laborum ab voluptatibus praesentium error, eius nobis reprehenderit laudantium tempora
                        voluptates
                        dignissimos excepturi quidem odit? Quia, dolor rem iste id cupiditate ipsam.
                        Laborum ab voluptatibus praesentium error, eius nobis reprehenderit laudantium tempora
                        voluptates
                        dignissimos excepturi quidem odit?</p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-9">
                    <h6 class="state-border"><strong>United States</strong></h6>
                </div>
                <div class="col-md-3">
                    <h6 class="state-border"><strong>International</strong></h6>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                </div>
                <div class="col-md-3">
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                </div>
                <div class="col-md-3">
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                    <div>State</div>
                </div>
                <div class="col-md-3">
                    <div>Canada</div>
                    <div>Columbia</div>
                    <div>Germany</div>
                    <div>Nicaragua</div>
                </div>
            </div>
        </div>

    </div>
</main>
{% endblock %}

app/templates/whoweare.html
{% extends 'layout.html' %}
{% set active_page='main.whoweare' -%}

{% block title %}
{{ super() }} | Who We Are
{% endblock %}

{% block body %}
{% endblock %}